### ISSUE TITLE
[Request] Could you add the possibility to choose the menu item with a letter?

### ISSUE THREAD

**Issue by GerdchenF** [averissimo/open-link-in-foreground#2]
Hi,

Could you add the possibility to choose the menu item with a letter?

Like the standard "Open link in a new Tab" where the T is underlined and can be used to call the item with the keyboard.

Something like "Open link in Foreground" with the F underlined and activiting the menu item by hitting the f key.

Regards,
Gerd

**Comment by averissimo** [comment]
Sounds nice, I'm uploading the new version with this right now
